WITH AVAILABLE_CARS AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    WHERE CAR_TYPE IN ('세단', 'SUV')
      AND NOT EXISTS (
          SELECT 1
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
          WHERE A.CAR_ID = B.CAR_ID
            AND B.START_DATE <= DATE '2022-11-30'
            AND B.END_DATE >= DATE '2022-11-01'
      )
),
DISCOUNTED_CARS AS (
    SELECT 
        A.CAR_ID,
        A.CAR_TYPE,
        FLOOR(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30) AS FEE
    FROM AVAILABLE_CARS A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
      ON A.CAR_TYPE = B.CAR_TYPE
    WHERE B.DURATION_TYPE = '30일 이상'
)
SELECT *
FROM DISCOUNTED_CARS
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
