WITH REVIEW AS (
    SELECT
          REST_ID
        , ROUND(AVG(REVIEW_SCORE), 2) AS REVIEW_AVG_SCORE
    FROM
        REST_REVIEW
    GROUP BY REST_ID
),
INFO AS (
    SELECT
          REST_ID
        , REST_NAME
        , FOOD_TYPE
        , FAVORITES
        , ADDRESS
    FROM
        REST_INFO
    WHERE ADDRESS LIKE '서울%'
)
SELECT
      I.*
    , R.REVIEW_AVG_SCORE AS SCORE
FROM INFO I
INNER JOIN REVIEW R
ON I.REST_ID = R.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;